'https://dlcdn.apache.org/maven/' = 'https://mirrors.aliyun.com/apache/maven/'
'https://go.dev/dl/' = 'https://golang.google.cn/dl/'
'https://gradle.org/releases/next-steps/?version=' = 'https://mirrors.cloud.tencent.com/gradle/gradle-%s-all.zip'
'https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/' = 'https://julialang-s3.julialang.org/bin/'
'https://nodejs.org/download/release/' = 'https://mirrors.huaweicloud.com/nodejs/'
'https://repo.anaconda.com/miniconda/' = 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/'
'https://storage.googleapis.com/flutter_infra_release/releases/stable/' = 'https://mirrors.tuna.tsinghua.edu.cn/flutter/flutter_infra/releases/stable/'
