flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['agg.exe']
linux = ['agg']
darwin = ['agg']

[binary_dirs]
windows = []
linux = []
darwin = []

[binary_rename]
name_flag = 'agg'
rename_to = 'agg'
