FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['agg.exe']
Linux = ['agg']
MacOS = ['agg']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'agg'
RenameTo = 'agg'
