flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['bazel.exe']
linux = ['bazel']
darwin = ['bazel']

[binary_dirs]
windows = []
linux = []
darwin = []

[binary_rename]
name_flag = 'bazel'
rename_to = 'bazel'
