FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['bazel.exe']
Linux = ['bazel']
MacOS = ['bazel']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'bazel'
RenameTo = 'bazel'
