FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['deps.edn', 'example-deps.edn']
Linux = ['deps.edn', 'example-deps.edn']
MacOS = ['deps.edn', 'example-deps.edn']

[BinaryDirs]
Windows = [['bin']]
Linux = [['bin']]
MacOS = [['bin']]
