flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['deps.edn', 'example-deps.edn']
linux = ['deps.edn', 'example-deps.edn']
darwin = ['deps.edn', 'example-deps.edn']

[binary_dirs]
windows = [['bin']]
linux = [['bin']]
darwin = [['bin']]
