flag_dir_excepted = false
additional_envs = []

[flag_files]
windows = ['bin', 'share']
linux = ['bin', 'share']
darwin = ['bin', 'share']

[binary_dirs]
windows = [['bin']]
linux = [['bin']]
darwin = [['bin']]
