FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['setup-x86_64.exe']
Linux = ['setup-x86_64.exe']
MacOS = ['setup-x86_64.exe']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'setup-x86_64'
RenameTo = 'cygwin-installer'
