FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['windows']
Linux = ['linux']
MacOS = ['osx']

[BinaryDirs]
Windows = [['windows', 'bin']]
Linux = [['linux', 'bin64']]
MacOS = [['osx', 'bin']]
