flag_dir_excepted = false
additional_envs = []

[flag_files]
windows = ['README.md', 'LICENSE', 'CODEOWNERS']
linux = ['README.md', 'LICENSE', 'CODEOWNERS']
darwin = ['README.md', 'LICENSE', 'CODEOWNERS']

[binary_dirs]
windows = [['bin']]
linux = [['bin']]
darwin = [['bin']]
