FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['bin', 'cmd', 'usr']
Linux = []
MacOS = []

[BinaryDirs]
Windows = [['bin'], ['usr', 'bin'], ['cmd'], ['mingw64', 'bin']]
Linux = []
MacOS = []
