FlagDirExcepted = false

[FlagFiles]
Windows = ['VERSION', 'LICENSE']
Linux = ['VERSION', 'LICENSE']
MacOS = ['VERSION', 'LICENSE']

[BinaryDirs]
Windows = [['bin']]
Linux = [['bin']]
MacOS = [['bin']]

[[AdditionalEnvs]]
Name = 'GOROOT'
Value = []
Version = ''
