FlagDirExcepted = false

[FlagFiles]
Windows = ['bin', 'lib', 'include']
Linux = ['bin', 'lib', 'include']
MacOS = ['bin', 'lib', 'include']

[BinaryDirs]
Windows = [['bin'], ['jre', 'bin']]
Linux = [['bin'], ['jre', 'bin']]
MacOS = [['bin'], ['jre', 'bin']]

[[AdditionalEnvs]]
Name = 'JAVA_HOME'
Value = []
Version = ''

[[AdditionalEnvs]]
Name = 'CLASSPATH'
Value = [['lib', 'dt.jar'], ['lib', 'tools.jar'], ['jre', 'lib', 'rt.jar']]
Version = 'major<=8'
