flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['README.md', 'LICENSE']
linux = ['README.md', 'LICENSE']
darwin = ['README.md', 'LICENSE']

[binary_dirs]
windows = []
linux = []
darwin = []
