FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['README.md', 'LICENSE']
Linux = ['README.md', 'LICENSE']
MacOS = ['README.md', 'LICENSE']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []
