FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['bin', 'lib', 'include']
Linux = ['bin', 'lib', 'include']
MacOS = ['bin', 'lib', 'include']

[BinaryDirs]
Windows = [['bin']]
Linux = [['bin']]
MacOS = [['bin']]
