FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['msys2-x86_64-latest.exe']
Linux = ['msys2-x86_64-latest.exe']
MacOS = ['msys2-x86_64-latest.exe']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'msys2-x86_64-latest'
RenameTo = 'msys2-installer'
