FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['bin', 'share']
Linux = ['bin', 'share']
MacOS = ['bin', 'share']

[BinaryDirs]
Windows = [['bin']]
Linux = [['bin']]
MacOS = [['bin']]
