FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['LICENSE', 'README.md']
Linux = ['LICENSE', 'README.md']
MacOS = ['LICENSE', 'README.md']

[BinaryDirs]
Windows = []
Linux = [['bin']]
MacOS = [['bin']]
