flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['tinymist.exe']
linux = ['tinymist']
darwin = ['tinymist']

[binary_dirs]
windows = []
linux = []
darwin = []

[binary_rename]
name_flag = 'tinymist'
rename_to = 'tinymist'
