FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['tinymist.exe']
Linux = ['tinymist']
MacOS = ['tinymist']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'tinymist'
RenameTo = 'tinymist'
