flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['tree-sitter.exe']
linux = ['tree-sitter']
darwin = ['tree-sitter']

[binary_dirs]
windows = []
linux = []
darwin = []

[binary_rename]
name_flag = 'tree-sitter'
rename_to = 'tree-sitter'
