FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['tree-sitter.exe']
Linux = ['tree-sitter']
MacOS = ['tree-sitter']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'tree-sitter'
RenameTo = 'tree-sitter'
