FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['typst-lsp.exe']
Linux = ['typst-lsp']
MacOS = ['typst-lsp']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'typst-lsp'
RenameTo = 'typst-lsp'
