flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['typst-preview.exe']
linux = ['typst-preview']
darwin = ['typst-preview']

[binary_dirs]
windows = []
linux = []
darwin = []

[binary_rename]
name_flag = 'typst-preview'
rename_to = 'typst-preview'
