FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['typst-preview.exe']
Linux = ['typst-preview']
MacOS = ['typst-preview']

[BinaryDirs]
Windows = []
Linux = []
MacOS = []

[BinaryRename]
NameFlag = 'typst-preview'
RenameTo = 'typst-preview'
