FlagDirExcepted = false
AdditionalEnvs = []

[FlagFiles]
Windows = ['cmd', 'v.exe']
Linux = ['cmd', 'v']
MacOS = ['cmd', 'v']

[BinaryDirs]
Windows = [[], ['cmd', 'tools']]
Linux = [[], ['cmd', 'tools']]
MacOS = [[], ['cmd', 'tools']]
