flag_dir_excepted = false
additional_envs = []

[flag_files]
windows = ['cmd', 'v.exe']
linux = ['cmd', 'v']
darwin = ['cmd', 'v']

[binary_dirs]
windows = [[], ['cmd', 'tools']]
linux = [[], ['cmd', 'tools']]
darwin = [[], ['cmd', 'tools']]
