flag_dir_excepted = true
additional_envs = []

[flag_files]
windows = ['wasmtime.exe', 'LICENSE']
linux = ['wasmtime', 'LICENSE']
darwin = ['wasmtime', 'LICENSE']

[binary_dirs]
windows = [[]]
linux = [[]]
darwin = [[]]
