FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['wasmtime.exe', 'LICENSE']
Linux = ['wasmtime', 'LICENSE']
MacOS = ['wasmtime', 'LICENSE']

[BinaryDirs]
Windows = [[]]
Linux = [[]]
MacOS = [[]]
