FlagDirExcepted = true
AdditionalEnvs = []

[FlagFiles]
Windows = ['README.md']
Linux = ['README.md']
MacOS = ['README.md']

[BinaryDirs]
Windows = [[], ['bin']]
Linux = [[], ['bin']]
MacOS = [[], ['bin']]
